#
# Makefile rules for compiling examples.
#

vpath %.f90 $(VPATHS)
vpath %.c   $(VPATHS)

$(EXE): $(OBJ)
ifdef MKVERBOSE
	$(FC) $(FFLAGS) $^ $(OUTPUT_OPTION) $(LDFLAGS)
else
	@echo "Linking..."
	@$(FC) $(FFLAGS) $^ $(OUTPUT_OPTION) $(LDFLAGS)
endif

build/%.o: %.f90
	@mkdir -p build
ifdef MKVERBOSE
	$(FC) $(FFLAGS) -c $< $(OUTPUT_OPTION)
else
	@echo "Building $<..."
	@$(FC) $(FFLAGS) -c $< $(OUTPUT_OPTION)
endif

build/%.o: %.c
	@mkdir -p build
ifdef MKVERBOSE
	$(CC) $(CFLAGS) -c $< $(OUTPUT_OPTION)
else
	@echo "Building $<..."
	@$(CC) $(CFLAGS) -c $< $(OUTPUT_OPTION)
endif

.PHONY: clean

clean:
	find . -name build | xargs rm -rf
	find . -name '*.exe' | xargs rm -f
	rm -f fort.* *.slog2 *.edf *.trc gmon.out

#
# MINIPFASST dependencies
#

build/sweeper_dtype.o:  build/pf_config.o
build/user_dtype.o:     build/pf_config.o
build/pf_dtype.o:       build/user_dtype.o build/sweeper_dtype.o
build/pf_utils.o:       build/pf_dtype.o build/sweeper.o
build/pf_hooks.o:       build/pf_dtype.o
build/pf_mpi.o:         build/pf_dtype.o
build/sweeper.o:        build/pf_hooks.o
build/pf_restrict.o:    build/pf_utils.o build/pf_hooks.o build/transfer.o
build/pf_interpolate.o: build/pf_restrict.o build/pf_hooks.o build/sweeper.o
build/pf_parallel.o:    build/pf_interpolate.o build/pf_hooks.o build/pf_mpi.o build/pf_timer.o
build/sdc_quadrature.o: build/pf_dtype.o build/sdc_poly.o
build/pf_quadrature.o:  build/sdc_quadrature.o
build/pf_options.o:     build/pf_dtype.o
build/pf_pfasst.o:      build/pf_utils.o build/pf_quadrature.o \
                        build/pf_hooks.o build/pf_options.o build/user.o
build/pfasst.o:         build/pf_parallel.o build/pf_pfasst.o \
                        build/sweeper.o build/pf_mpi.o build/pf_options.o
